version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: grupo07
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
