---
- hosts: test
  user: root
  vars: 
     packages: ['nginx', 'php56u' ,'php56u-fpm' ,'php56u-mysql' ]

  tasks:
    - copy:
       src: /etc/yum.repos.d/nginx.repo 
       dest: /etc/yum.repos.d
       owner: root
       group: root
       mode: 0644

    - name: Install ius repo
      yum: name=https://centos7.iuscommunity.org/ius-release.rpm state=installed

    - name: Install php php-fpm php-mysql
      yum: name={{ packages }} state=installed
      with_items: packages
      notify:
        - start-enable nginx
        - start-enable php-fpm

    - name: php-fpm configuration 1/3
      lineinfile: dest=/etc/php-fpm.d/www.conf regexp="^;listen =" line="listen = /var/run/php-fpm/php-fpm.sock" state=present
      notify:
        - restart php-fpm

    - name: php-fpm configuration 2/3
      lineinfile: dest=/etc/php-fpm.d/www.conf regexp="^;listen.group" line="listen.group = nginx" state=present
      notify:
        - restart php-fpm

    - name: php-fpm configuration 3/3
      lineinfile: dest=/etc/php-fpm.d/www.conf regexp="^;listen.owner" line="listen.owner = nginx" state=present
      notify:
        - restart php-fpm

    - name: se crea "sites-avaible"
      file: path=/etc/nginx/sites-available state=directory owner=root group=root

    - name: se crea "sites-enabled"
      file: path=/etc/nginx/sites-enabled state=directory owner=root group=root

    - copy:
       src: /etc/nginx/sites-available/opencart.conf
       dest: /etc/nginx/conf.d/
       owner: root
       group: root
       mode: 0644

    - copy:
       src: /etc/pki/tls/certs/grupo07.mosorio.me.crt
       dest: /etc/pki/tls/certs
       owner: root
       group: root
       mode: 0644

    - copy:
       src: /etc/pki/tls/private/private.key
       dest: /etc/pki/tls/private
       owner: root
       group: root
       mode: 0644

  handlers:
    - name: start-enable nginx
      service: name=nginx state=started enabled=yes

    - name: start-enable php-fpm
      service: name=php-fpm state=started enabled=yes

    - name: restart php-fpm
      service: name=php-fpm state=restarted

    - name: restart nginx
      service: name=nginx state=restarted    
...

